config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'users/my_portfolio'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'my_connections', to: 'users#my_connections'
  get 'search_user', to: 'users#search'
  get 'refresh_tracked_stocks', to: 'stocks#refresh_tracked_stocks'
  resources :stocks, only: [:show]
  resources :users, only: [:show], :constraints => { :id => /[0-9|]+/ }
  resources :user_stocks, only: [:create, :destroy]
  resources :connections, only: [:create, :destroy]
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/connection.rb
class Connection < ApplicationRecord
  belongs_to :user
  belongs_to :contact, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :ticker, presence: true

  def self.check_db(symbol)
    where(ticker: symbol).first
  end

  def get_quote
    client = get_client
    client.quote(self.ticker)
  end

  def get_news
    client = get_client
    client.news(self.ticker)
  end

  private 
  
  def get_client
    IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_client[:sandbox_tokens][:publishable_token],
      secret_token: Rails.application.credentials.iex_client[:sandbox_tokens][:secret_token],
      endpoint: 'https://sandbox.iexapis.com/v1')
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :connections
  has_many :contacts, through: :connections

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end

  def under_stock_limit?
    stocks.count < 10
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  def full_name
    if first_name? || last_name?
      "#{first_name.capitalize} #{last_name.capitalize}"
    else
      "User"
    end
  end

  def self.search(param)
    param.strip!
    results = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless results
    results
  end

  def self.first_name_matches(param)
    matches("first_name", param)
  end

  def self.last_name_matches(param)
    matches("last_name", param)
  end

  def self.email_matches(param)
    matches("email", param)
  end

  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def not_connected_with?(user_id)
    return true unless self.contacts.where(id: user_id).exists?
    false
  end

end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
  
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController

  def create
    new_connection = Connection.new(user_id: current_user.id, contact_id: params[:contact])
    if new_connection.save
      contact = User.find(params[:contact])
      flash[:notice] = "You have successfully started following #{contact.full_name}."
    else
      flash[:alert] = "Something went wrong."
    end
    redirect_to my_connections_path
  end

  def destroy
    contact = User.find(params[:id])
    connection = Connection.where(user_id: current_user.id, contact_id: contact.id).first
    connection.destroy
    flash[:notice] = "You have successfully unfollowed #{contact.full_name}."
    redirect_to my_connections_path
  end
  
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def show
    stock = Stock.new(ticker: params[:id])
    begin
      @quote = stock.get_quote
      @news = stock.get_news
      db_lookup = Stock.check_db(params[:id])
      @stock_id = db_lookup.nil? ? nil : db_lookup.id
    # If API call fails, stock was invalid
    rescue
      flash[:alert] = "Invalid stock. Returned to portfolio view."
      redirect_to my_portfolio_path
    end
  end

  def search
    if params[:stock].present?

      begin
        # Check if exists in DB, else create new Stock object
        db_lookup = Stock.check_db(params[:stock])
        stock = db_lookup.nil? ? Stock.new(ticker: params[:stock]) : db_lookup

        @quote = stock.get_quote
        @stock_id = stock.id

        respond_to do |format|
          format.js { render partial: 'users/stock_result' }
        end

      # If API call fails, the stock call was invalid
      rescue
        respond_to do |format|
          flash.now[:alert] = "Please enter a valid symbol to search"
          format.js { render partial: 'users/stock_result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a symbol to search"
        format.js { render partial: 'users/stock_result' }
      end
    end
  end

  def refresh_tracked_stocks
    @user = User.find(params[:user_id])
    respond_to do |format|
      flash.now[:alert] = "Please enter a symbol to search"
      format.js { render partial: 'users/refresh_tracked_stocks' }
    end
  end

end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

  def create
    stock = Stock.check_db(params[:ticker])
    if stock.blank?
      stock = Stock.new(ticker: params[:ticker])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "#{stock.ticker} has been successfully added to your portfolio."
    redirect_to request.referrer
  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    user_stock.destroy
    flash[:notice] = "You have successfully removed #{stock.ticker} from your portfolio."
    redirect_to my_portfolio_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def my_portfolio
    @user = current_user.stocks
  end

  def my_connections
    @user_contacts = current_user.contacts
  end

  def show
    @user = User.find(params[:id])
  end

  def search
    if params[:user].present?
      @results = User.search(params[:user])
      @results = current_user.except_current_user(@results)
      if !@results.empty?
        respond_to do |format|
          format.js { render partial: 'users/user_result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "No users found"
          format.js { render partial: 'users/user_result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a user to search"
        format.js { render partial: 'users/user_result' }
      end
    end
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    if user_signed_in?
      redirect_to my_portfolio_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_message.html.erb
<div class="alert alert-dismissible fade show <%= alert_type %> <%= add_class%>" role="alert">
  <%= alert_message %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/_messages.html.erb
<% add_class = add_class.nil? ? "" : add_class %>
<% if notice %>
  <%= render "layouts/message", alert_type: "alert-success", alert_message: notice, add_class: add_class %>
<% end %>
<% if alert %>
  <%= render "layouts/message", alert_type: "alert-danger", alert_message: alert, add_class: add_class %>
<% end %>
<% flash.clear %>

app/views/layouts/_navigation.html.erb
<% if request.path != root_path %>
  <nav class="navbar fixed-top navbar-expand-md navbar-light bg-light">
    <div class="container">
      <%= link_to "Stock Tracker", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <% if current_user %>
            <ul class="navbar-nav mr-auto">
              <li class="nav-item user-dropdown-collapse <%= 'active' if request.path == my_portfolio_path %>">
                <%= link_to "My Portfolio", my_portfolio_path, class: "nav-link" %>
              </li>
              <li class="nav-item user-dropdown-collapse <%= 'active' if request.path == my_connections_path %>">
                <%= link_to "Connections", my_connections_path, class: "nav-link" %>
              </li>
              <div id="user-dropdown-expanded">
                <li class="nav-item <%= 'active' if request.path == my_portfolio_path %>">
                  <%= link_to my_portfolio_path, class: "nav-link" do %>
                    <%= fa_icon "book", class: "mr-2 nav-expanded-icon" %>My Portfolio
                  <% end %>
                </li>
                <li class="nav-item <%= 'active' if request.path == my_connections_path %>">
                  <%= link_to my_connections_path, class: "nav-link" do %>
                    <%= fa_icon "users", class: "mr-2 nav-expanded-icon" %>Connections
                  <% end %>
                </li>
                <li class="nav-item <%= 'active' if request.path == edit_user_registration_path %>">
                  <%= link_to edit_user_registration_path, class: "nav-link" do %>
                    <%= fa_icon "edit", class: "mr-2 nav-expanded-icon" %>Edit profile
                  <% end %>
                </li>
                <div class="dropdown-divider"></div>
                <li class="nav-item">
                  <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
                    <%= fa_icon "sign-out", class: "mr-2 nav-expanded-icon" %>Logout
                  <% end %>
                </li>
              </div>
            </ul>
            <ul class="navbar-nav ml-auto">
              <li class="nav-item dropdown user-dropdown-collapse">
                <%= link_to "#", { class: "nav-link dropdown-toggle mr-2", id:"navbarDropdown", role:"button", data: { toggle:"dropdown"}, aria: { haspopup:"true", expanded:"false"}}  do %>
                  <%= fa_icon "user", class: "mr-1" %><%= current_user.full_name %>
                <% end %>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
                    <%= fa_icon "edit", class: "mr-2" %>Edit profile
                  <% end %>
                  <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
                    <%= fa_icon "sign-out", class: "mr-2" %>Logout
                  <% end %>
                </div>
              </li>
            </ul>
          <% else %>
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <%= link_to "Sign Up", new_user_registration_path, class: "nav-link text-primary mr-2" %>
              </li>
              <li class="nav-item">
                <%= link_to "Login", new_user_session_path, class: "btn btn-primary mr-2" %>
              </li>
            </ul>
          <% end %>
        </div>
      
    </div>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Stock Tracker</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render "layouts/navigation" %>
  <%= render "layouts/messages", add_class: "top-message" %>
  <%= yield %>
</body>

</html>

app/views/shared/_format_stock_delta.html.erb
<% change_class = ""%>
<% change_text = "#{number_with_precision(change, precision: 2)}"%>
<% if change > 0 %>
  <% change_class = "text-success"%>
  <% change_text = "+#{change_text}"%>
<% elsif change < 0 %>
  <% change_class = "text-danger"%>
<% end %>
<span class="<%= change_class %>"><%=change_text%></span>

app/views/shared/_format_stock_delta_percent.html.erb
<% change_class = ""%>
<% if change > 0 %>
  <% change_class = "text-success"%>
<% elsif change < 0 %>
  <% change_class = "text-danger"%>
<% end %>
<span class="<%= change_class %>">(<%=percent%>)</span>

app/views/stocks/show.html.erb
<div class="container page-container">

  <div class="row no-gutters">
    <div class="col-10">
      <h1 class="mr-2"><%= @quote.company_name %> <small>(<%= @quote.symbol %>)</small></h1>
    </div>
    <div class="col-2 text-right">
      <a class="btn btn-outline-secondary dropdown-toggle dropdown-toggle-split options-dropdown" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>
      <div class="dropdown-menu dropdown-menu-right">
        <% if current_user.can_track_stock?(@quote.symbol) %>
          <%= link_to "Track", user_stocks_path(user: current_user, ticker: @quote.symbol), method: :post, class: "dropdown-item" %>
        <% else %>
          <%= link_to "Untrack", user_stock_path(@stock_id), method: :delete, class: "dropdown-item",
            data: { confirm: "Are you sure you want to stop tracking #{@quote.company_name} (#{@quote.symbol})?" } %>
        <% end %>
      </div>
    </div>
  </div>

  <h2>
    <%= number_with_precision(@quote.latest_price, precision: 2) %>
    <small>
      <%= render  "shared/format_stock_delta", change: @quote.change %>
      <%= render  "shared/format_stock_delta_percent", change: @quote.change, percent: @quote.change_percent_s %>
    </small>
  </h2>
  <p class="mb-0">As of <%= @quote.latest_source %> on <%= @quote.latest_time %></p>
  
  <% if current_user.stock_already_tracked?(@quote.symbol) %>
    <span class="badge badge-success">Tracking</span>
  <% end %>

  <div class="row mt-3">

    <div class="col-md-8 col-lg-4">
      <table class="table">
        <tbody>
          <tr>
            <td class="no-border-top"> Previous Close</td>
            <td class="no-border-top text-right font-weight-bold"><%= number_with_precision(@quote.previous_close, precision: 2) %></td>
          </tr>
          <tr>
            <td>Open</td>
            <td class="text-right font-weight-bold">Unavailable</td>
          </tr>
          <tr>
            <td>Day's Range</td>
            <td class="text-right font-weight-bold">Unavailable</td>
          </tr>
          <tr>
            <td>52 Week Range</td>
            <td class="text-right font-weight-bold"><%= @quote.week_52_low %> - <%= @quote.week_52_high %></td>
          </tr>
          <tr>
            <td>Volume</td>
            <td class="text-right font-weight-bold">Unavailable</td>
          </tr>
          <tr>
            <td>Avg. Volume</td>
            <td class="text-right font-weight-bold"><%= number_with_delimiter(@quote.avg_total_volume) %></td>
          </tr>
          <tr>
            <td>Market Cap</td>
            <td class="text-right font-weight-bold"><%= number_to_human(@quote.market_cap, precision: 4) %></td>
          </tr>
          <tr>
            <td>PE Ratio</td>
            <td class="text-right font-weight-bold"><%= @quote.pe_ratio %></td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="col-lg-1"></div>

    <div class="col-lg-7" id="news-container">
      <div class="row">
        <div class="col">
          <h2 id="news-header">News</h2>
        </div>
      </div>

      <% @news.each do |article| %>
      <div class="mb-4 mt-3">
        <div class="row">
          <div class="col">
            <%= link_to  "/", class:"link-style" do %>
              <h5 class="mb-0"><%= article.headline %></h5>
            <% end %>
          </div>
        </div>
        <div class="row mb-2">
          <div class="col text-right font-italic">
            <small><%= article.datetime.strftime("%b %-d, %Y %l:%M %P")%></small>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <p class="pl-1 pr-1"><%= article.summary %></p>
          </div>
        </div>
      </div>
      <% end %>

    </div>

  </div>
</div>

app/views/users/_contacts_table.html.erb
<h3>Following</h3>

<div class="card shadow-sm bg-white rounded mt-2">
  <ul class="list-group list-group-flush">
    <% @user_contacts.each do |contact| %>
      <li class="list-group-item contact" data-link="<%= user_path(contact) %>">
        <div class="row">
          <div class="col-12 col-sm-6">
            <div>
              <span class="mr-2"><%= contact.full_name %></span>
            </div>
            <div>
              <span class="mr-2"><small><%= contact.email %></small></span>
            </div>
          </div>
          <div class="col-12 col-sm-6" id="contact-table-stock-container">
            <% contact.stocks.each do |stock| %>
              <%= link_to stock.ticker, stock_path(stock.ticker), class:"badge badge-primary contact-stock-badge" %>
            <%end %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/users/_refresh_tracked_stocks.js.erb
document.querySelector('#stock-tracker').innerHTML = '<%= j render 'users/stocks_table.html', user: @user %>'

app/views/users/_stock_result.html.erb
<%= render  "layouts/messages" %>

<% if @quote %>
  <div class="card shadow-sm bg-white rounded mt-2">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <div class="row">
          <div class="col-9 col-sm-6">
            <div>
              <span class="mr-2">
                <%= @quote.company_name %> <small class="mr-3">(<%= @quote.symbol %>)</small>
              </span>
            </div>
            <div>
              <span class="mr-2">
                <strong><%= number_with_precision(@quote.latest_price, precision: 2) %></strong>
                <%= render "shared/format_stock_delta", change: @quote.change %>
                <%= render  "shared/format_stock_delta_percent", change: @quote.change, percent: @quote.change_percent_s %>
              </span>
            </div>
          </div>
          <div class="col-3 col-sm-6">
            <div class="row">
              <div class="col d-flex justify-content-end">
                <%= link_to "View", stock_path(@quote.symbol), class:"btn btn-sm btn-info search-buttons mr-2" %>
                <div class="results-extra-options">
                  <% if current_user.can_track_stock?(@quote.symbol) %>
                    <%= link_to "Track", user_stocks_path(user: current_user, ticker: @quote.symbol), method: :post, class:"btn btn-sm btn-success search-buttons" %>
                  <% elsif current_user.stock_already_tracked?(@quote.symbol) %>
                    <%= link_to "Untrack", user_stock_path(@stock_id), method: :delete, class: "btn btn-sm btn-danger search-buttons",
                      data: { confirm: "Are you sure you want to stop tracking #{@quote.symbol}?" } %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </li>
    </ul>
  </div>
<% end %>

app/views/users/_stock_result.js.erb
document.querySelector('#stock-results-container').innerHTML = '<%= j render 'users/stock_result.html' %>'

app/views/users/_stocks_table.html.erb
<div id="stock-tracker">
  <div class="row">
    <div class="col-10">
      <h3>Tracked Stocks 
        <% if user.stocks.count > 0 %>
          <small>(<%= user.stocks.count %>/10)</small></h3>
        <% end %>
    </div>
    <div class="col-2 text-right">
      <%= link_to refresh_tracked_stocks_path(user_id: user.id), class: "no-text-decoration", remote: true, method: :get do%>
        <h3><%= fa_icon "history", id: "stocks-table-refresh-icon"%></h3>
      <% end %>
    </div>
  </div>

  
  
  <div class="card shadow-sm bg-white rounded mt-2">
    <ul class="list-group list-group-flush">
      <% user.stocks.each do |stock| %>
      <% quote = stock.get_quote %>
        <li class="list-group-item contact" data-link="<%= stock_path(quote.symbol) %>">
          <div class="row">
            <div class="col">
              <div>
                <span><%= quote.company_name %> <small>(<%= quote.symbol %>)</small></span>
              </div>
              <div>
                <span>
                  <strong><%= number_with_precision(quote.latest_price, precision: 2) %></strong>
                  <%= render "shared/format_stock_delta", change: quote.change %>
                  <%= render  "shared/format_stock_delta_percent", change: quote.change, percent: quote.change_percent_s %>
                </span>
              </div>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>

  <% latest_time = user.stocks.first.get_quote.latest_time %>
  <div class="row text-right">
    <div class="col-12">
      <small class="font-italic">As of <%= latest_time %> EST</small>
    </div>
  </div>

</div>

app/views/users/_user_result.html.erb
<%= render  "layouts/messages" %>

<% if @results && @results.count > 0 %>
  <div class="card shadow-sm bg-white rounded mt-2">
    <ul class="list-group list-group-flush">
      <% @results.each do |contact| %>
        <li class="list-group-item">
          <div class="row">
            <div class="col-9">
              <div>
                <span class="mr-2"><%= contact.full_name %></span>
              </div>
              <div>
                <span class="mr-2"><small><%= contact.email %></small></span>
              </div>
            </div>
            <div class="col-3">
              <div class="row">
                <div class="col d-flex justify-content-end">
                  <%= link_to "View", contact, class:"btn btn-sm btn-info search-buttons mr-2" %>
                  <div class="results-extra-options">
                    <% if current_user.not_connected_with?(contact.id) %>
                      <%= link_to "Follow", connections_path(contact: contact), method: :post, class:"btn btn-sm btn-success search-buttons" %>
                    <% else %>
                      <%= link_to "Unfollow", connection_path(contact), method: :delete, class: "btn btn-sm btn-danger search-buttons",
                        data: { confirm: "Are you sure you want to stop following #{contact.full_name}?" } %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_user_result.js.erb
document.querySelector('#user-results-container').innerHTML = '<%= j render 'users/user_result.html' %>'

app/views/users/connections.html.erb
<div class="container page-container">

  <h1>My Connections</h1>

  <div class="search-area">
    <h3>Search Stocks</h3>
    <%= form_tag search_stock_path, remote: true, method: :get do %>
      <div class="input-group">
        <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true , class: 'form-control form-control-lg'%>
        <div class="input-group-append">
          <%= button_tag type: :submit, class: 'btn btn-success' do %>
            <%= fa_icon 'search 2x' %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <div id="results-container">
    <%= render "users/result" %>
  </div>

  <div class="tracking-container">
    <% if !@user_contacts.empty? %>
      <%= render "contacts_table" %>
    <% else %>
      <h5 class="font-weight-light font-italic text-center">You currently have no connections. Search and add contacts to build your connections.</h5>
    <% end %>
  </div>

</div>

app/views/users/my_connections.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-8 page-container">

      <h1 class="display-4">My Connections</h1>

      <div class="search-area shadow-sm bg-white rounded">
        <h3>Search Users</h3>
        <%= form_tag search_user_path, remote: true, method: :get do %>
          <div class="input-group">
            <%= text_field_tag :user, params[:user], placeholder: "Search by name or email", class: 'form-control form-control-lg'%>
            <div class="input-group-append">
              <%= button_tag type: :submit, class: 'btn btn-secondary' do %>
                <%= fa_icon 'search 2x' %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>

      <div id="user-results-container">
        <%= render "users/user_result" %>
      </div>

      <div class="tracking-container">
        <% if !@user_contacts.empty? %>
          <%= render "contacts_table" %>
        <% else %>
          <h5 class="font-weight-light font-italic text-center">You currently have no connections. Search and add contacts to build your connections.</h5>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/users/my_portfolio.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 page-container">

    <h1 class="display-4">My Portfolio</h1>

    <div class="search-area">
      <h3>Search Stocks</h3>
      <%= form_tag search_stock_path, remote: true, method: :get do %>
        <div class="input-group">
          <%= text_field_tag :stock, params[:stock], placeholder: "Enter stock symbol", class: 'form-control form-control-lg'%>
          <div class="input-group-append">
            <%= button_tag type: :submit, class: 'btn btn-secondary' do %>
              <%= fa_icon 'search 2x' %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

    <div id="stock-results-container">
      <%= render "users/stock_result" %>
    </div>

    <div class="tracking-container">
      <% if !current_user.stocks.empty? %>
        <%= render "stocks_table", user: current_user %>
      <% else %>
        <h5 class="font-weight-light font-italic text-center">You are currently not tracking any stocks. Search and add stocks to build your portfolio.</h5>
      <% end %>
    </div>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 page-container">

      <div class="row no-gutters">
        <div class="col-10">
          <h1 class="display-4"><%= @user.full_name %>'s Profile</h1>
        </div>
        <div class="col-2 text-right">
          <% if current_user != @user %>
            <div class="dropdown">
              <a class="btn btn-outline-secondary dropdown-toggle dropdown-toggle-split options-dropdown" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>
              <div class="dropdown-menu dropdown-menu-right">
                <% if current_user.not_connected_with?(@user.id) %>
                  <%= link_to "Follow", connections_path(contact: @user.id), method: :post, class: "dropdown-item" %>
                <% else %>
                  <%= link_to "Unfollow", connection_path(@user), method: :delete, class: "dropdown-item",
                    data: { confirm: "Are you sure you want to stop following #{@user.full_name}" } %>
                <% end %>
              </div>
            </div>
          <% end %>
          </div>
      </div>

      <div class="row pl-3">
        <% if !current_user.not_connected_with?(@user.id) %>
          <span class="badge badge-success">Following</span>
        <% end %>
      </div>

      <div class="tracking-container">
        <% if !@user.stocks.empty? %>
          <%= render "stocks_table", user: @user%>
        <% else %>
          <h5 class="font-weight-light font-italic text-center"><%= @user.full_name %> is currently not tracking any stocks.</h5>
        <% end %>
      </div>

    </div>
  </div>
</div>